name: CI Checks

on:
    pull_request:
        branches: [master]

jobs:
    tests:
        name: ğŸ§ª Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Prepare
              uses: ./.github/actions/prepare-project/

            - name: Run tests
              run: pnpm test

    checks:
        name: ğŸ” Static Analysis & Code Quality
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Prepare
              uses: ./.github/actions/prepare-project/

            - name: Check circular dependency
              run: pnpm check-circular-dependency

            - name: Check linting
              run: pnpm lint

            - name: Check format
              run: pnpm format

            - name: Check style lint
              run: pnpm lint:scss

            - name: Check deadcode
              run: pnpm knip

    build:
        name: ğŸ—ï¸ Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Prepare
              uses: ./.github/actions/prepare-project/

            - name: Check storybook build
              run: pnpm build:storybook

            - name: Check packages build
              run: pnpm -r --if-present build
